import type { Metadata } from "next";
import {Exo } from "next/font/google";
import "./globals.css";

const exo = Exo({ subsets: ["latin"], weight: "200" });


export const metadata: Metadata = {
  title: "Tracking Application",
  description: "Generated by El",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={exo.className}
      >
        {children}
      </body>
    </html>
  );
}
3